name: C/C++ CI

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install dependancies
      run: apt update && apt install libwayland-dev libxkbcommon-dev
    - name: install glfw
      run: git clone https://github.com/glfw/glfw.git && cd glfw && mkdir build && cd build && cmake -D GLFW_BUILD_X11=0 .. && make && make install
    - name: build wayland-app
      run: mkdir build && cd build && cmake .. && make
    - name: test
      run: test -f build/wayland-app