name: C/C++ CI

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build wayland-app
      run: mkdir build && cd build && cmake .. && make
    - name: test
      run: test -f build/wayland-app
